spring:
  application:
    name: eureka-service
server:
  port: 9091

eureka:
  instance:
    hostname: localhost
#    hostname: eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/