server:
  port: 9093

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

zuul:
  routes:
    house:
      path: /house/**
      serviceId: house-service
#      url: http://example.com/users_service
    appeal:
      path: /appeal/**
      serviceId: appeal-service
#      url: http://example.com/users_service